language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=leonardo
- BOARD=micro
- BOARD=megaatmega2560
- BOARD=due
- BOARD=uno
- BOARD=yun

script:
- set -eo pipefail;
- for e in examples/* tests/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
